### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by che-122** [sirbrillig/mixed-indent-warning#12]
To reproduce:
1. Split panes in Atom
2. Type anything in a file with mixed indent

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.5
**Thrown From**: [mixed-indent-warning](https://github.com/sirbrillig/mixed-indent-warning) package, v0.3.0
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker
```

**Comment by Arcanemagus** [comment]
This is a known bug in the currently released version of Linter, unfortunately fixing it requires almost as much work as the UI rewrite... which is already done (and this fixed in) for the upcoming Linter v2.

**Comment by sirbrillig** [comment]
Thanks for the report, @faroutchris! It sounds like this is a Linter issue (thanks for the info @Arcanemagus), but I'll investigate it too and see if I can do something to help.

**Comment by sirbrillig** [comment]
I think this is fixed now.
