### ISSUE TITLE
Breaks autoindent

### ISSUE THREAD

**Issue by gregplaysguitar** [sirbrillig/mixed-indent-warning#13]
With this linter enabled, the editor always defaults to the global indentation setting rather than the per-language setting when opening a file. When the file is saved the indentation is corrected. It also stops the auto-detect-indentation package from working.

**Comment by Arcanemagus** [comment]
Are you sure that it is this package? There is nothing in the code here that should be causing the behavior you describe. The only thing this does is call out to [mixedindentlint](https://github.com/sirbrillig/mixedindentlint) with the contents of the file, and then transform the results into a format that Linter understands.

**Comment by gregplaysguitar** [comment]
Sorry, I thought I had pinned it on this package but now it's happening again with it disabled.
