### ISSUE TITLE
Don't highlight blank lines

### ISSUE THREAD

**Issue by ChristinWhite** [sirbrillig/mixed-indent-warning#2]
Is there a quick way to set this package not to flag blank lines as mixed indentation? I use blank lines for spacing and organization pretty frequently which makes it much more difficult to scan through a document to make sure indentation is consistent.

Thanks, other than this I love the package, great work!

**Comment by polarathene** [comment]
+1 ran into this as well. It'd also be nice if you had a setting for ignoring indents for comment blocks:
`/*
 *
 */`
Not sure how to format that correctly, it'd be vertical with 1 space indent to align the `*`'s

**Comment by sirbrillig** [comment]
Yes indeed. Both of these are on my to-do list. In fact, I just came here to make sure there was an issue for this, and here we are!

**Comment by sirbrillig** [comment]
Should be fixed by #4
