### ISSUE TITLE
Feature request: consider all leading whitespace

### ISSUE THREAD

**Issue by Sod-Almighty** [sirbrillig/mixed-indent-warning#20]
Lines that contain mixed leading whitespace currently do not trigger this add-on, unless the mistake is at the start of the line:
```
<TAB><TAB><SPACE><TAB>code...
```
Please modify the add-on to show a warning for lines such as the above.

**Comment by sirbrillig** [comment]
That's a good idea, although it is a different direction for the plugin since then it is looking for mixed spaces and tabs on a single line. This plugin uses the `mixedindentlint` library, so I've moved this request over to there: https://github.com/sirbrillig/mixedindentlint/issues/5
