### ISSUE TITLE
Add to official linters list

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/mixed-indent-warning#7]
Find out how to add to [official linters list](http://atomlinter.github.io/).

**Comment by keplersj** [comment]
Just ask?

**Comment by sirbrillig** [comment]
Haha, good idea @kepler0! I also just located [the repo](https://github.com/AtomLinter/atomlinter.github.io), so I can make a PR myself. Thanks!

**Comment by sirbrillig** [comment]
https://github.com/AtomLinter/atomlinter.github.io/pull/21
